/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NZQ; 

import NZQ.Forms.LoginForm;

public class App {
    public static void main(String[] args) {
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }
}
