/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NZQ.Forms;

import static NZQ.Forms.AddPersonOrGroup.VALID_EMAIL_ADDRESS_REGEX;
import java.awt.ComponentOrientation;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author muhamadtalebi
 */
public class DateFilterTarazNameh extends javax.swing.JFrame {
        public static final Pattern VALID_DATE_REGEX = Pattern.compile("[۰-۹0-9]+");
public static final Pattern VALID_DIGIT_REGEX = Pattern.compile("[\\d]{2}");
public static final Pattern VALID_DAY_REGEX = Pattern.compile("[\\d]{1,30}");
public static final Pattern VALID_MONTH_REGEX = Pattern.compile("[\\d]{1,12}");

    /**
     * Creates new form DateFilterTarazNameh
     */
    public DateFilterTarazNameh() {
        initComponents();
        dailyButton.setComponentOrientation( ComponentOrientation.RIGHT_TO_LEFT );
        monthlyButton.setComponentOrientation( ComponentOrientation.RIGHT_TO_LEFT );
        yearlyButton.setComponentOrientation( ComponentOrientation.RIGHT_TO_LEFT );
        dateValidationErrorLabel.setVisible(false);
        dayDateField.setColumns(2);
        
          
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dailyButton = new javax.swing.JRadioButton();
        monthlyButton = new javax.swing.JRadioButton();
        yearlyButton = new javax.swing.JRadioButton();
        filterTarikhHeaderLabel = new javax.swing.JLabel();
        taarikhLabel = new javax.swing.JLabel();
        dayDateField = new javax.swing.JTextField();
        placeHolderDate2 = new javax.swing.JLabel();
        monthDateField = new javax.swing.JTextField();
        yearDateField = new javax.swing.JTextField();
        placeHolderDate1 = new javax.swing.JLabel();
        filterApply = new javax.swing.JButton();
        dateValidationErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(dailyButton);
        dailyButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dailyButton.setSelected(true);
        dailyButton.setText("روزانه");
        dailyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(monthlyButton);
        monthlyButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        monthlyButton.setText("ماهانه");
        monthlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(yearlyButton);
        yearlyButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        yearlyButton.setText("سالانه");
        yearlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyButtonActionPerformed(evt);
            }
        });

        filterTarikhHeaderLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        filterTarikhHeaderLabel.setText("فیلتر تاریخ");

        taarikhLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        taarikhLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taarikhLabel.setText("تاریخ :");

        placeHolderDate2.setText("/");

        yearDateField.setColumns(4);
        yearDateField.setDragEnabled(false);
        yearDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearDateFieldActionPerformed(evt);
            }
        });

        placeHolderDate1.setText("/");

        filterApply.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        filterApply.setText("اعمال");
        filterApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterApplyActionPerformed(evt);
            }
        });

        dateValidationErrorLabel.setForeground(new java.awt.Color(250, 0, 0));
        dateValidationErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateValidationErrorLabel.setText("date validation!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(yearDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterTarikhHeaderLabel)
                            .addComponent(filterApply)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(placeHolderDate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(placeHolderDate2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dayDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taarikhLabel)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dailyButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(monthlyButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(yearlyButton, javax.swing.GroupLayout.Alignment.TRAILING))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(dateValidationErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterTarikhHeaderLabel)
                .addGap(60, 60, 60)
                .addComponent(dailyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthlyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearlyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taarikhLabel)
                    .addComponent(dayDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placeHolderDate2)
                    .addComponent(monthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placeHolderDate1))
                .addGap(30, 30, 30)
                .addComponent(filterApply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateValidationErrorLabel)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyButtonActionPerformed
         if(yearlyButton.isSelected()){
            dayDateField.setEditable(false);
            dayDateField.setEnabled(false);
            monthDateField.setEditable(false);
            monthDateField.setEnabled(false);
        }
            else{
            dayDateField.setEditable(true);
            dayDateField.setEnabled(true);
            monthDateField.setEditable(true);
            monthDateField.setEnabled(true);
                               
        }
    
    }//GEN-LAST:event_yearlyButtonActionPerformed

    private void yearDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearDateFieldActionPerformed
    
    }//GEN-LAST:event_yearDateFieldActionPerformed
    private boolean isDateValid(){
    Matcher matcher = VALID_DATE_REGEX.matcher(dayDateField.getText());
    Matcher matcherDigitDay = VALID_DIGIT_REGEX.matcher(dayDateField.getText());
    Matcher matcherDigitMonth = VALID_DIGIT_REGEX.matcher(monthDateField.getText());
    Matcher matcherLimitMonth = VALID_MONTH_REGEX.matcher(monthDateField.getText());
    Matcher matcherLimitDay = VALID_DAY_REGEX.matcher(dayDateField.getText());
    Matcher matcherMonth = VALID_DATE_REGEX.matcher(monthDateField.getText());
    Matcher matcherYear = VALID_DATE_REGEX.matcher(yearDateField.getText());
        if (!matcher.find() &&
                !matcherMonth.find() &&
                !matcherYear.find() &&
                !matcherLimitDay.find() &&
                !matcherLimitMonth.find() &&
                !matcherDigitDay.find() &&
                !matcherDigitMonth.find()) {
            dateValidationErrorLabel.setText("تاریخ معتبر نیست!");
            dateValidationErrorLabel.setVisible(true);
            return false;
        }
        return true;
    }
    private void dailyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyButtonActionPerformed
        if(dailyButton.isSelected()){
            dayDateField.setEditable(true);
            dayDateField.setEnabled(true);
            monthDateField.setEditable(true);
            monthDateField.setEnabled(true);
        }
    }//GEN-LAST:event_dailyButtonActionPerformed

    private void monthlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyButtonActionPerformed
        if(monthlyButton.isSelected()){
            dayDateField.setEditable(false);
            dayDateField.setEnabled(false);
            monthDateField.setEditable(true);
            monthDateField.setEnabled(true);
        }
        else{
            dayDateField.setEditable(true);
            dayDateField.setEnabled(true);
        }
    }//GEN-LAST:event_monthlyButtonActionPerformed

    private void filterApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterApplyActionPerformed
isDateValid();        // TODO add your handling code here:
    }//GEN-LAST:event_filterApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateFilterTarazNameh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateFilterTarazNameh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateFilterTarazNameh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateFilterTarazNameh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateFilterTarazNameh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dailyButton;
    private javax.swing.JLabel dateValidationErrorLabel;
    private javax.swing.JTextField dayDateField;
    private javax.swing.JButton filterApply;
    private javax.swing.JLabel filterTarikhHeaderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monthDateField;
    private javax.swing.JRadioButton monthlyButton;
    private javax.swing.JLabel placeHolderDate1;
    private javax.swing.JLabel placeHolderDate2;
    private javax.swing.JLabel taarikhLabel;
    private javax.swing.JTextField yearDateField;
    private javax.swing.JRadioButton yearlyButton;
    // End of variables declaration//GEN-END:variables
}
